name: "ä¸Šç­"

on:
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --optimize-autoloader --no-dev

      - name: Run sign
        env:
          MOGUDING_DEVICE: ${{ secrets.DEVICE }}
          MOGUDING_PHONE: ${{ secrets.PHONE }}
          MOGUDING_PASSWORD: ${{ secrets.PASSWORD }}
          MOGUDING_PROVINCE: ${{ secrets.PROVINCE }}
          MOGUDING_CITY: ${{ secrets.CITY }}
          MOGUDING_ADDRESS: ${{ secrets.ADDRESS }}
          MOGUDING_LONGITUDE: ${{ secrets.LONGITUDE }}
          MOGUDING_LATITUDE: ${{ secrets.LATITUDE }}
          MOGUDING_TYPE: "START"
          MOGUDING_DESCRIPTION: ${{ secrets.DESCRIPTION }}
          MOGUDING_SCT_KEY: ${{ secrets.SENDKEY }}
        run: php artisan moguding
      - id: timestamp
        run: echo "::set-output name=timestamp::$(timestamp +%s)"
      - name: Restore the previous run result
        uses: actions/cache@v2
        with:
         path: |
           run_result
         key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
         restore-keys: |
           ${{ github.run_id }}-${{ github.job }}-
      - id: run_result
        run: cat run_result 2>/dev/null || echo 'default'
      - uses: actions/checkout@v2
        if: steps.run_result.outputs.run_result != 'success'
      - run: echo "::set-output name=run_result::success" > run_result
